services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    
    volummes: 
      - postgres_data:/var/lib/postgresql/data

    nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro


volumes:
  postgres_data
