services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends on:
      - postgres

  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb